# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\gui\radianceeditnuclidedialog.ui'
#
# Created: Fri Jul 15 11:15:47 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_REditNuclideDialog(object):
    def setupUi(self, REditNuclideDialog):
        REditNuclideDialog.setObjectName("REditNuclideDialog")
        REditNuclideDialog.setWindowModality(QtCore.Qt.NonModal)
        REditNuclideDialog.resize(640, 480)
        REditNuclideDialog.setMinimumSize(QtCore.QSize(640, 480))
        REditNuclideDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(REditNuclideDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtGui.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nuclideNameLabel = QtGui.QLabel(REditNuclideDialog)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nuclideNameLabel.setFont(font)
        self.nuclideNameLabel.setObjectName("nuclideNameLabel")
        self.horizontalLayout_2.addWidget(self.nuclideNameLabel)
        self.errorLabel = QtGui.QLabel(REditNuclideDialog)
        self.errorLabel.setStyleSheet("QLabel {\n"
"    background: url(:/Radiance/icons/error.png);\n"
"    background-position: center left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left: 20px;\n"
"}")
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_2.addWidget(self.errorLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.elementLabel = QtGui.QLabel(REditNuclideDialog)
        self.elementLabel.setObjectName("elementLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.elementLabel)
        self.elementComboBox = QtGui.QComboBox(REditNuclideDialog)
        self.elementComboBox.setEditable(True)
        self.elementComboBox.setMaxVisibleItems(20)
        self.elementComboBox.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.elementComboBox.setMinimumContentsLength(15)
        self.elementComboBox.setFrame(True)
        self.elementComboBox.setObjectName("elementComboBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.elementComboBox)
        self.atomicMassLabel = QtGui.QLabel(REditNuclideDialog)
        self.atomicMassLabel.setObjectName("atomicMassLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.atomicMassLabel)
        self.atomicMassSpinBox = QtGui.QSpinBox(REditNuclideDialog)
        self.atomicMassSpinBox.setAccelerated(True)
        self.atomicMassSpinBox.setMinimum(1)
        self.atomicMassSpinBox.setMaximum(999)
        self.atomicMassSpinBox.setProperty("value", 1)
        self.atomicMassSpinBox.setObjectName("atomicMassSpinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.atomicMassSpinBox)
        self.atomicNumberLabel = QtGui.QLabel(REditNuclideDialog)
        self.atomicNumberLabel.setObjectName("atomicNumberLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.atomicNumberLabel)
        self.atomicNumberSpinBox = QtGui.QSpinBox(REditNuclideDialog)
        self.atomicNumberSpinBox.setEnabled(False)
        self.atomicNumberSpinBox.setMaximum(999)
        self.atomicNumberSpinBox.setObjectName("atomicNumberSpinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.atomicNumberSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.topLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.deleteButton = QtGui.QPushButton(REditNuclideDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Radiance/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setObjectName("deleteButton")
        self.topLayout.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.topLayout)
        self.nuclideToolBox = QtGui.QToolBox(REditNuclideDialog)
        self.nuclideToolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nuclideToolBox.setObjectName("nuclideToolBox")
        self.gammaSpectrumPageWidget = QtGui.QWidget()
        self.gammaSpectrumPageWidget.setGeometry(QtCore.QRect(0, 0, 620, 296))
        self.gammaSpectrumPageWidget.setObjectName("gammaSpectrumPageWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gammaSpectrumPageWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gammaSpectrumTableView = QtGui.QTableView(self.gammaSpectrumPageWidget)
        self.gammaSpectrumTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.gammaSpectrumTableView.setTabKeyNavigation(False)
        self.gammaSpectrumTableView.setAlternatingRowColors(True)
        self.gammaSpectrumTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.gammaSpectrumTableView.setCornerButtonEnabled(False)
        self.gammaSpectrumTableView.setObjectName("gammaSpectrumTableView")
        self.verticalLayout_2.addWidget(self.gammaSpectrumTableView)
        self.nuclideToolBox.addItem(self.gammaSpectrumPageWidget, "")
        self.verticalLayout.addWidget(self.nuclideToolBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.correctnessErrorLabel = QtGui.QLabel(REditNuclideDialog)
        self.correctnessErrorLabel.setEnabled(True)
        self.correctnessErrorLabel.setStyleSheet("QLabel {\n"
"    background: url(:/Radiance/icons/error.png);\n"
"    background-position: center left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left: 20px;\n"
"}")
        self.correctnessErrorLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.correctnessErrorLabel.setObjectName("correctnessErrorLabel")
        self.horizontalLayout.addWidget(self.correctnessErrorLabel)
        self.saveButton = QtGui.QPushButton(REditNuclideDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Radiance/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setAutoDefault(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtGui.QPushButton(REditNuclideDialog)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(REditNuclideDialog)
        self.nuclideToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), REditNuclideDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(REditNuclideDialog)

    def retranslateUi(self, REditNuclideDialog):
        REditNuclideDialog.setWindowTitle(QtGui.QApplication.translate("REditNuclideDialog", "Edit nuclide", None, QtGui.QApplication.UnicodeUTF8))
        self.errorLabel.setText(QtGui.QApplication.translate("REditNuclideDialog", "Already exists.", None, QtGui.QApplication.UnicodeUTF8))
        self.elementLabel.setText(QtGui.QApplication.translate("REditNuclideDialog", "Element", None, QtGui.QApplication.UnicodeUTF8))
        self.atomicMassLabel.setText(QtGui.QApplication.translate("REditNuclideDialog", "Atomic mass", None, QtGui.QApplication.UnicodeUTF8))
        self.atomicNumberLabel.setText(QtGui.QApplication.translate("REditNuclideDialog", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("REditNuclideDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.nuclideToolBox.setItemText(self.nuclideToolBox.indexOf(self.gammaSpectrumPageWidget), QtGui.QApplication.translate("REditNuclideDialog", "Gamma spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.correctnessErrorLabel.setText(QtGui.QApplication.translate("REditNuclideDialog", "Check the correctness of data input.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("REditNuclideDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("REditNuclideDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import radiance_rc
