# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\gui\radiancemainwindow.ui'
#
# Created: Fri Jul 15 11:15:47 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RadianceMainWindow(object):
    def setupUi(self, RadianceMainWindow):
        RadianceMainWindow.setObjectName("RadianceMainWindow")
        RadianceMainWindow.resize(800, 600)
        RadianceMainWindow.setMinimumSize(QtCore.QSize(640, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Radiance/icons/shield.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RadianceMainWindow.setWindowIcon(icon)
        RadianceMainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(RadianceMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tab_1.setFont(font)
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.tab_1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.nuclideComboBoxPage1 = QtGui.QComboBox(self.groupBox_2)
        self.nuclideComboBoxPage1.setMaxVisibleItems(25)
        self.nuclideComboBoxPage1.setMinimumContentsLength(20)
        self.nuclideComboBoxPage1.setObjectName("nuclideComboBoxPage1")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.nuclideComboBoxPage1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.radioactiveDecayDoubleSpinBoxPage1 = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioactiveDecayDoubleSpinBoxPage1.sizePolicy().hasHeightForWidth())
        self.radioactiveDecayDoubleSpinBoxPage1.setSizePolicy(sizePolicy)
        self.radioactiveDecayDoubleSpinBoxPage1.setMinimumSize(QtCore.QSize(120, 0))
        self.radioactiveDecayDoubleSpinBoxPage1.setDecimals(5)
        self.radioactiveDecayDoubleSpinBoxPage1.setMinimum(0.01)
        self.radioactiveDecayDoubleSpinBoxPage1.setMaximum(1000000000.0)
        self.radioactiveDecayDoubleSpinBoxPage1.setObjectName("radioactiveDecayDoubleSpinBoxPage1")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.radioactiveDecayDoubleSpinBoxPage1)
        self.verticalLayout_10.addLayout(self.formLayout_2)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gammaSpectrumTableViewPage1 = QtGui.QTableView(self.groupBox_7)
        self.gammaSpectrumTableViewPage1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gammaSpectrumTableViewPage1.setTabKeyNavigation(False)
        self.gammaSpectrumTableViewPage1.setAlternatingRowColors(True)
        self.gammaSpectrumTableViewPage1.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.gammaSpectrumTableViewPage1.setCornerButtonEnabled(False)
        self.gammaSpectrumTableViewPage1.setObjectName("gammaSpectrumTableViewPage1")
        self.verticalLayout_4.addWidget(self.gammaSpectrumTableViewPage1)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.materialComboBox = QtGui.QComboBox(self.groupBox)
        self.materialComboBox.setMaxVisibleItems(10)
        self.materialComboBox.setMinimumContentsLength(20)
        self.materialComboBox.setObjectName("materialComboBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.materialComboBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.materialThicknessDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialThicknessDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.materialThicknessDoubleSpinBox.setSizePolicy(sizePolicy)
        self.materialThicknessDoubleSpinBox.setMinimumSize(QtCore.QSize(75, 0))
        self.materialThicknessDoubleSpinBox.setMinimum(0.01)
        self.materialThicknessDoubleSpinBox.setMaximum(99999.99)
        self.materialThicknessDoubleSpinBox.setObjectName("materialThicknessDoubleSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.materialThicknessDoubleSpinBox)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.materialDensityDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialDensityDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.materialDensityDoubleSpinBox.setSizePolicy(sizePolicy)
        self.materialDensityDoubleSpinBox.setMinimumSize(QtCore.QSize(75, 0))
        self.materialDensityDoubleSpinBox.setMinimum(0.01)
        self.materialDensityDoubleSpinBox.setMaximum(99999.99)
        self.materialDensityDoubleSpinBox.setObjectName("materialDensityDoubleSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.materialDensityDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.splitter)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.distanceLabel = QtGui.QLabel(self.groupBox_3)
        self.distanceLabel.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.distanceLabel.setWordWrap(False)
        self.distanceLabel.setObjectName("distanceLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.distanceLabel)
        self.distanceDoubleSpinBoxPage1 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceDoubleSpinBoxPage1.sizePolicy().hasHeightForWidth())
        self.distanceDoubleSpinBoxPage1.setSizePolicy(sizePolicy)
        self.distanceDoubleSpinBoxPage1.setMinimumSize(QtCore.QSize(100, 0))
        self.distanceDoubleSpinBoxPage1.setDecimals(3)
        self.distanceDoubleSpinBoxPage1.setMinimum(0.001)
        self.distanceDoubleSpinBoxPage1.setMaximum(999999.999)
        self.distanceDoubleSpinBoxPage1.setObjectName("distanceDoubleSpinBoxPage1")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.distanceDoubleSpinBoxPage1)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Radiance/icons/shape_square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_1, icon1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_4 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.nuclideComboBoxPage2 = QtGui.QComboBox(self.groupBox_4)
        self.nuclideComboBoxPage2.setMaxVisibleItems(25)
        self.nuclideComboBoxPage2.setMinimumContentsLength(20)
        self.nuclideComboBoxPage2.setObjectName("nuclideComboBoxPage2")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.nuclideComboBoxPage2)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.radioactiveDecayDoubleSpinBoxPage2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioactiveDecayDoubleSpinBoxPage2.sizePolicy().hasHeightForWidth())
        self.radioactiveDecayDoubleSpinBoxPage2.setSizePolicy(sizePolicy)
        self.radioactiveDecayDoubleSpinBoxPage2.setMinimumSize(QtCore.QSize(120, 0))
        self.radioactiveDecayDoubleSpinBoxPage2.setDecimals(5)
        self.radioactiveDecayDoubleSpinBoxPage2.setMinimum(0.01)
        self.radioactiveDecayDoubleSpinBoxPage2.setMaximum(1000000000.0)
        self.radioactiveDecayDoubleSpinBoxPage2.setObjectName("radioactiveDecayDoubleSpinBoxPage2")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.radioactiveDecayDoubleSpinBoxPage2)
        self.verticalLayout_11.addLayout(self.formLayout_4)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gammaSpectrumTableViewPage2 = QtGui.QTableView(self.groupBox_8)
        self.gammaSpectrumTableViewPage2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gammaSpectrumTableViewPage2.setTabKeyNavigation(False)
        self.gammaSpectrumTableViewPage2.setAlternatingRowColors(True)
        self.gammaSpectrumTableViewPage2.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.gammaSpectrumTableViewPage2.setCornerButtonEnabled(False)
        self.gammaSpectrumTableViewPage2.setObjectName("gammaSpectrumTableViewPage2")
        self.verticalLayout_6.addWidget(self.gammaSpectrumTableViewPage2)
        self.verticalLayout_11.addWidget(self.groupBox_8)
        self.groupBox_5 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.layeredMaterialComboBox = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layeredMaterialComboBox.sizePolicy().hasHeightForWidth())
        self.layeredMaterialComboBox.setSizePolicy(sizePolicy)
        self.layeredMaterialComboBox.setMaxVisibleItems(10)
        self.layeredMaterialComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.layeredMaterialComboBox.setMinimumContentsLength(20)
        self.layeredMaterialComboBox.setFrame(True)
        self.layeredMaterialComboBox.setObjectName("layeredMaterialComboBox")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.layeredMaterialComboBox)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.layeredMaterialThicknessDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.layeredMaterialThicknessDoubleSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layeredMaterialThicknessDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.layeredMaterialThicknessDoubleSpinBox.setSizePolicy(sizePolicy)
        self.layeredMaterialThicknessDoubleSpinBox.setMinimumSize(QtCore.QSize(75, 0))
        self.layeredMaterialThicknessDoubleSpinBox.setMinimum(0.01)
        self.layeredMaterialThicknessDoubleSpinBox.setMaximum(99999.99)
        self.layeredMaterialThicknessDoubleSpinBox.setObjectName("layeredMaterialThicknessDoubleSpinBox")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.layeredMaterialThicknessDoubleSpinBox)
        self.verticalLayout_12.addLayout(self.formLayout_5)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layeredMaterialLayersTableView = QtGui.QTableView(self.groupBox_9)
        self.layeredMaterialLayersTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.layeredMaterialLayersTableView.setTabKeyNavigation(False)
        self.layeredMaterialLayersTableView.setAlternatingRowColors(True)
        self.layeredMaterialLayersTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.layeredMaterialLayersTableView.setCornerButtonEnabled(False)
        self.layeredMaterialLayersTableView.setObjectName("layeredMaterialLayersTableView")
        self.verticalLayout_7.addWidget(self.layeredMaterialLayersTableView)
        self.verticalLayout_12.addWidget(self.groupBox_9)
        self.verticalLayout_9.addWidget(self.splitter_2)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.distanceLabel_2 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.distanceLabel_2.setFont(font)
        self.distanceLabel_2.setStyleSheet("* {\n"
"    color: rgb(215, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.distanceLabel_2.setWordWrap(False)
        self.distanceLabel_2.setObjectName("distanceLabel_2")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.distanceLabel_2)
        self.distanceDoubleSpinBoxPage2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceDoubleSpinBoxPage2.sizePolicy().hasHeightForWidth())
        self.distanceDoubleSpinBoxPage2.setSizePolicy(sizePolicy)
        self.distanceDoubleSpinBoxPage2.setMinimumSize(QtCore.QSize(100, 0))
        self.distanceDoubleSpinBoxPage2.setDecimals(3)
        self.distanceDoubleSpinBoxPage2.setMinimum(0.001)
        self.distanceDoubleSpinBoxPage2.setMaximum(999999.999)
        self.distanceDoubleSpinBoxPage2.setObjectName("distanceDoubleSpinBoxPage2")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.distanceDoubleSpinBoxPage2)
        self.verticalLayout_8.addLayout(self.formLayout_6)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Radiance/icons/layers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.correctnessErrorLabel = QtGui.QLabel(self.centralwidget)
        self.correctnessErrorLabel.setEnabled(True)
        self.correctnessErrorLabel.setStyleSheet("QLabel {\n"
"    background: url(:/Radiance/icons/error.png);\n"
"    background-position: center left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left: 20px;\n"
"}")
        self.correctnessErrorLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.correctnessErrorLabel.setObjectName("correctnessErrorLabel")
        self.horizontalLayout.addWidget(self.correctnessErrorLabel)
        self.simulateButton = QtGui.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Radiance/icons/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simulateButton.setIcon(icon3)
        self.simulateButton.setAutoDefault(True)
        self.simulateButton.setDefault(True)
        self.simulateButton.setObjectName("simulateButton")
        self.horizontalLayout.addWidget(self.simulateButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        RadianceMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RadianceMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        RadianceMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(RadianceMainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        RadianceMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionReference = QtGui.QAction(RadianceMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Radiance/icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReference.setIcon(icon4)
        self.actionReference.setObjectName("actionReference")
        self.actionExit = QtGui.QAction(RadianceMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Radiance/icons/door_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.actionContents = QtGui.QAction(RadianceMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Radiance/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContents.setIcon(icon6)
        self.actionContents.setObjectName("actionContents")
        self.actionAbout = QtGui.QAction(RadianceMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Radiance/icons/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBackup = QtGui.QAction(RadianceMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Radiance/icons/database_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackup.setIcon(icon8)
        self.actionBackup.setObjectName("actionBackup")
        self.actionReports = QtGui.QAction(RadianceMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Radiance/icons/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReports.setIcon(icon9)
        self.actionReports.setObjectName("actionReports")
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionReference)
        self.menuTools.addAction(self.actionReports)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionBackup)
        self.menuHelp.addAction(self.actionContents)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionReference)
        self.toolBar.addAction(self.actionReports)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionContents)

        self.retranslateUi(RadianceMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), RadianceMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(RadianceMainWindow)
        RadianceMainWindow.setTabOrder(self.simulateButton, self.tabWidget)
        RadianceMainWindow.setTabOrder(self.tabWidget, self.nuclideComboBoxPage1)
        RadianceMainWindow.setTabOrder(self.nuclideComboBoxPage1, self.radioactiveDecayDoubleSpinBoxPage1)
        RadianceMainWindow.setTabOrder(self.radioactiveDecayDoubleSpinBoxPage1, self.materialComboBox)
        RadianceMainWindow.setTabOrder(self.materialComboBox, self.materialThicknessDoubleSpinBox)
        RadianceMainWindow.setTabOrder(self.materialThicknessDoubleSpinBox, self.materialDensityDoubleSpinBox)
        RadianceMainWindow.setTabOrder(self.materialDensityDoubleSpinBox, self.distanceDoubleSpinBoxPage1)
        RadianceMainWindow.setTabOrder(self.distanceDoubleSpinBoxPage1, self.nuclideComboBoxPage2)
        RadianceMainWindow.setTabOrder(self.nuclideComboBoxPage2, self.radioactiveDecayDoubleSpinBoxPage2)
        RadianceMainWindow.setTabOrder(self.radioactiveDecayDoubleSpinBoxPage2, self.layeredMaterialComboBox)
        RadianceMainWindow.setTabOrder(self.layeredMaterialComboBox, self.layeredMaterialThicknessDoubleSpinBox)
        RadianceMainWindow.setTabOrder(self.layeredMaterialThicknessDoubleSpinBox, self.distanceDoubleSpinBoxPage2)
        RadianceMainWindow.setTabOrder(self.distanceDoubleSpinBoxPage2, self.gammaSpectrumTableViewPage1)
        RadianceMainWindow.setTabOrder(self.gammaSpectrumTableViewPage1, self.gammaSpectrumTableViewPage2)
        RadianceMainWindow.setTabOrder(self.gammaSpectrumTableViewPage2, self.layeredMaterialLayersTableView)

    def retranslateUi(self, RadianceMainWindow):
        RadianceMainWindow.setWindowTitle(QtGui.QApplication.translate("RadianceMainWindow", "Radiance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Source parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RadianceMainWindow", "Nuclide", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RadianceMainWindow", "Radioactive decay, mCi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Gamma spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Screen parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RadianceMainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RadianceMainWindow", "Thickness, cm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RadianceMainWindow", "Density, g/cm³", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Other parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.distanceLabel.setText(QtGui.QApplication.translate("RadianceMainWindow", "Distance between source and calculation point, cm", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("RadianceMainWindow", "Single-layered screen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Source parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RadianceMainWindow", "Nuclide", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RadianceMainWindow", "Radioactive decay, mCi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Gamma spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Screen parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RadianceMainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RadianceMainWindow", "Total thickness, cm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "Other parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.distanceLabel_2.setText(QtGui.QApplication.translate("RadianceMainWindow", "Distance between source and calculation point, cm", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("RadianceMainWindow", "Multi-layered screen", None, QtGui.QApplication.UnicodeUTF8))
        self.correctnessErrorLabel.setText(QtGui.QApplication.translate("RadianceMainWindow", "Check the correctness of data input.", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButton.setText(QtGui.QApplication.translate("RadianceMainWindow", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("RadianceMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("RadianceMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReference.setText(QtGui.QApplication.translate("RadianceMainWindow", "&Reference...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReference.setShortcut(QtGui.QApplication.translate("RadianceMainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("RadianceMainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("RadianceMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContents.setText(QtGui.QApplication.translate("RadianceMainWindow", "Documentation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContents.setToolTip(QtGui.QApplication.translate("RadianceMainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContents.setShortcut(QtGui.QApplication.translate("RadianceMainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("RadianceMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setText(QtGui.QApplication.translate("RadianceMainWindow", "&Backup...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setToolTip(QtGui.QApplication.translate("RadianceMainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setShortcut(QtGui.QApplication.translate("RadianceMainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReports.setText(QtGui.QApplication.translate("RadianceMainWindow", "R&eports...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReports.setShortcut(QtGui.QApplication.translate("RadianceMainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))

import radiance_rc
