# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\gui\radiancereferencedialog.ui'
#
# Created: Fri Jul 15 11:15:47 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RadianceReferenceDialog(object):
    def setupUi(self, RadianceReferenceDialog):
        RadianceReferenceDialog.setObjectName("RadianceReferenceDialog")
        RadianceReferenceDialog.setWindowModality(QtCore.Qt.NonModal)
        RadianceReferenceDialog.resize(640, 480)
        RadianceReferenceDialog.setMinimumSize(QtCore.QSize(640, 480))
        RadianceReferenceDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(RadianceReferenceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(RadianceReferenceDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.nuclidesTabWidget = QtGui.QWidget()
        self.nuclidesTabWidget.setObjectName("nuclidesTabWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.nuclidesTabWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nuclideTopLayout = QtGui.QHBoxLayout()
        self.nuclideTopLayout.setObjectName("nuclideTopLayout")
        self.nuclideComboBox = QtGui.QComboBox(self.nuclidesTabWidget)
        self.nuclideComboBox.setMaxVisibleItems(20)
        self.nuclideComboBox.setMinimumContentsLength(20)
        self.nuclideComboBox.setObjectName("nuclideComboBox")
        self.nuclideTopLayout.addWidget(self.nuclideComboBox)
        self.editNuclideButton = QtGui.QPushButton(self.nuclidesTabWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Radiance/icons/page_white_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editNuclideButton.setIcon(icon)
        self.editNuclideButton.setCheckable(False)
        self.editNuclideButton.setAutoDefault(False)
        self.editNuclideButton.setObjectName("editNuclideButton")
        self.nuclideTopLayout.addWidget(self.editNuclideButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.nuclideTopLayout.addItem(spacerItem)
        self.addNuclideButton = QtGui.QPushButton(self.nuclidesTabWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Radiance/icons/page_white_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNuclideButton.setIcon(icon1)
        self.addNuclideButton.setAutoDefault(False)
        self.addNuclideButton.setObjectName("addNuclideButton")
        self.nuclideTopLayout.addWidget(self.addNuclideButton)
        self.verticalLayout_2.addLayout(self.nuclideTopLayout)
        self.nuclideCategoriesToolBox = QtGui.QToolBox(self.nuclidesTabWidget)
        self.nuclideCategoriesToolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nuclideCategoriesToolBox.setObjectName("nuclideCategoriesToolBox")
        self.nuclideGammaSpectrumPage = QtGui.QWidget()
        self.nuclideGammaSpectrumPage.setGeometry(QtCore.QRect(0, 0, 596, 326))
        self.nuclideGammaSpectrumPage.setObjectName("nuclideGammaSpectrumPage")
        self.horizontalLayout = QtGui.QHBoxLayout(self.nuclideGammaSpectrumPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nuclideGammaSpectrumTableView = QtGui.QTableView(self.nuclideGammaSpectrumPage)
        self.nuclideGammaSpectrumTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.nuclideGammaSpectrumTableView.setTabKeyNavigation(False)
        self.nuclideGammaSpectrumTableView.setAlternatingRowColors(True)
        self.nuclideGammaSpectrumTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.nuclideGammaSpectrumTableView.setCornerButtonEnabled(False)
        self.nuclideGammaSpectrumTableView.setObjectName("nuclideGammaSpectrumTableView")
        self.horizontalLayout.addWidget(self.nuclideGammaSpectrumTableView)
        self.nuclideCategoriesToolBox.addItem(self.nuclideGammaSpectrumPage, "")
        self.verticalLayout_2.addWidget(self.nuclideCategoriesToolBox)
        self.tabWidget.addTab(self.nuclidesTabWidget, "")
        self.materialsTabWidget = QtGui.QWidget()
        self.materialsTabWidget.setObjectName("materialsTabWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.materialsTabWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.materialTopLayout = QtGui.QHBoxLayout()
        self.materialTopLayout.setObjectName("materialTopLayout")
        self.materialComboBox = QtGui.QComboBox(self.materialsTabWidget)
        self.materialComboBox.setMaxVisibleItems(20)
        self.materialComboBox.setMinimumContentsLength(20)
        self.materialComboBox.setObjectName("materialComboBox")
        self.materialTopLayout.addWidget(self.materialComboBox)
        self.editMaterialButton = QtGui.QPushButton(self.materialsTabWidget)
        self.editMaterialButton.setIcon(icon)
        self.editMaterialButton.setAutoDefault(False)
        self.editMaterialButton.setObjectName("editMaterialButton")
        self.materialTopLayout.addWidget(self.editMaterialButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.materialTopLayout.addItem(spacerItem1)
        self.addMaterialButton = QtGui.QPushButton(self.materialsTabWidget)
        self.addMaterialButton.setIcon(icon1)
        self.addMaterialButton.setAutoDefault(False)
        self.addMaterialButton.setObjectName("addMaterialButton")
        self.materialTopLayout.addWidget(self.addMaterialButton)
        self.verticalLayout_4.addLayout(self.materialTopLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rhoLabel = QtGui.QLabel(self.materialsTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rhoLabel.sizePolicy().hasHeightForWidth())
        self.rhoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.rhoLabel.setFont(font)
        self.rhoLabel.setObjectName("rhoLabel")
        self.horizontalLayout_2.addWidget(self.rhoLabel)
        self.rhoValueLabel = QtGui.QLabel(self.materialsTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rhoValueLabel.sizePolicy().hasHeightForWidth())
        self.rhoValueLabel.setSizePolicy(sizePolicy)
        self.rhoValueLabel.setObjectName("rhoValueLabel")
        self.horizontalLayout_2.addWidget(self.rhoValueLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.materialCategoriesToolBox = QtGui.QToolBox(self.materialsTabWidget)
        self.materialCategoriesToolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.materialCategoriesToolBox.setObjectName("materialCategoriesToolBox")
        self.materialDoseBuildupFactorPage = QtGui.QWidget()
        self.materialDoseBuildupFactorPage.setGeometry(QtCore.QRect(0, 0, 596, 278))
        self.materialDoseBuildupFactorPage.setObjectName("materialDoseBuildupFactorPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.materialDoseBuildupFactorPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.top_label = QtGui.QLabel(self.materialDoseBuildupFactorPage)
        self.top_label.setTextFormat(QtCore.Qt.PlainText)
        self.top_label.setAlignment(QtCore.Qt.AlignCenter)
        self.top_label.setObjectName("top_label")
        self.verticalLayout_5.addWidget(self.top_label)
        self.doseBuildUpFactorLayout = QtGui.QHBoxLayout()
        self.doseBuildUpFactorLayout.setObjectName("doseBuildUpFactorLayout")
        self.left_label = QtGui.QLabel(self.materialDoseBuildupFactorPage)
        self.left_label.setTextFormat(QtCore.Qt.PlainText)
        self.left_label.setObjectName("left_label")
        self.doseBuildUpFactorLayout.addWidget(self.left_label)
        self.materialDoseBuildupFactorTableView = QtGui.QTableView(self.materialDoseBuildupFactorPage)
        self.materialDoseBuildupFactorTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.materialDoseBuildupFactorTableView.setTabKeyNavigation(False)
        self.materialDoseBuildupFactorTableView.setAlternatingRowColors(True)
        self.materialDoseBuildupFactorTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialDoseBuildupFactorTableView.setCornerButtonEnabled(False)
        self.materialDoseBuildupFactorTableView.setObjectName("materialDoseBuildupFactorTableView")
        self.doseBuildUpFactorLayout.addWidget(self.materialDoseBuildupFactorTableView)
        self.verticalLayout_5.addLayout(self.doseBuildUpFactorLayout)
        self.materialCategoriesToolBox.addItem(self.materialDoseBuildupFactorPage, "")
        self.materialMassAttenuationCoefficientPage = QtGui.QWidget()
        self.materialMassAttenuationCoefficientPage.setGeometry(QtCore.QRect(0, 0, 89, 89))
        self.materialMassAttenuationCoefficientPage.setObjectName("materialMassAttenuationCoefficientPage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.materialMassAttenuationCoefficientPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.materialMassAttenuationCoefficientTableView = QtGui.QTableView(self.materialMassAttenuationCoefficientPage)
        self.materialMassAttenuationCoefficientTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.materialMassAttenuationCoefficientTableView.setTabKeyNavigation(False)
        self.materialMassAttenuationCoefficientTableView.setAlternatingRowColors(True)
        self.materialMassAttenuationCoefficientTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialMassAttenuationCoefficientTableView.setCornerButtonEnabled(False)
        self.materialMassAttenuationCoefficientTableView.setObjectName("materialMassAttenuationCoefficientTableView")
        self.verticalLayout_6.addWidget(self.materialMassAttenuationCoefficientTableView)
        self.materialCategoriesToolBox.addItem(self.materialMassAttenuationCoefficientPage, "")
        self.verticalLayout_4.addWidget(self.materialCategoriesToolBox)
        self.tabWidget.addTab(self.materialsTabWidget, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.materialTopLayout_2 = QtGui.QHBoxLayout()
        self.materialTopLayout_2.setObjectName("materialTopLayout_2")
        self.multiLayeredMaterialComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiLayeredMaterialComboBox.sizePolicy().hasHeightForWidth())
        self.multiLayeredMaterialComboBox.setSizePolicy(sizePolicy)
        self.multiLayeredMaterialComboBox.setMaxVisibleItems(20)
        self.multiLayeredMaterialComboBox.setMinimumContentsLength(50)
        self.multiLayeredMaterialComboBox.setObjectName("multiLayeredMaterialComboBox")
        self.materialTopLayout_2.addWidget(self.multiLayeredMaterialComboBox)
        self.editMultiLayeredMaterialButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMultiLayeredMaterialButton.sizePolicy().hasHeightForWidth())
        self.editMultiLayeredMaterialButton.setSizePolicy(sizePolicy)
        self.editMultiLayeredMaterialButton.setIcon(icon)
        self.editMultiLayeredMaterialButton.setAutoDefault(False)
        self.editMultiLayeredMaterialButton.setObjectName("editMultiLayeredMaterialButton")
        self.materialTopLayout_2.addWidget(self.editMultiLayeredMaterialButton)
        self.addMultiLayeredMaterialButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMultiLayeredMaterialButton.sizePolicy().hasHeightForWidth())
        self.addMultiLayeredMaterialButton.setSizePolicy(sizePolicy)
        self.addMultiLayeredMaterialButton.setIcon(icon1)
        self.addMultiLayeredMaterialButton.setAutoDefault(False)
        self.addMultiLayeredMaterialButton.setObjectName("addMultiLayeredMaterialButton")
        self.materialTopLayout_2.addWidget(self.addMultiLayeredMaterialButton)
        self.verticalLayout_3.addLayout(self.materialTopLayout_2)
        self.nuclideCategoriesToolBox_2 = QtGui.QToolBox(self.tab)
        self.nuclideCategoriesToolBox_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nuclideCategoriesToolBox_2.setObjectName("nuclideCategoriesToolBox_2")
        self.multiLayeredMaterialLayersPage = QtGui.QWidget()
        self.multiLayeredMaterialLayersPage.setGeometry(QtCore.QRect(0, 0, 596, 326))
        self.multiLayeredMaterialLayersPage.setObjectName("multiLayeredMaterialLayersPage")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.multiLayeredMaterialLayersPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.materialLayersTableView = QtGui.QTableView(self.multiLayeredMaterialLayersPage)
        self.materialLayersTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.materialLayersTableView.setTabKeyNavigation(False)
        self.materialLayersTableView.setAlternatingRowColors(True)
        self.materialLayersTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialLayersTableView.setCornerButtonEnabled(False)
        self.materialLayersTableView.setObjectName("materialLayersTableView")
        self.horizontalLayout_4.addWidget(self.materialLayersTableView)
        self.nuclideCategoriesToolBox_2.addItem(self.multiLayeredMaterialLayersPage, "")
        self.verticalLayout_3.addWidget(self.nuclideCategoriesToolBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.closeButton = QtGui.QPushButton(RadianceReferenceDialog)
        self.closeButton.setAutoDefault(True)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(RadianceReferenceDialog)
        self.tabWidget.setCurrentIndex(0)
        self.nuclideCategoriesToolBox.setCurrentIndex(0)
        self.materialCategoriesToolBox.setCurrentIndex(0)
        self.nuclideCategoriesToolBox_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), RadianceReferenceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RadianceReferenceDialog)

    def retranslateUi(self, RadianceReferenceDialog):
        RadianceReferenceDialog.setWindowTitle(QtGui.QApplication.translate("RadianceReferenceDialog", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.editNuclideButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.addNuclideButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.nuclideCategoriesToolBox.setItemText(self.nuclideCategoriesToolBox.indexOf(self.nuclideGammaSpectrumPage), QtGui.QApplication.translate("RadianceReferenceDialog", "Gamma spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nuclidesTabWidget), QtGui.QApplication.translate("RadianceReferenceDialog", "Nuclides", None, QtGui.QApplication.UnicodeUTF8))
        self.editMaterialButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.addMaterialButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.rhoLabel.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "ρ", None, QtGui.QApplication.UnicodeUTF8))
        self.top_label.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "μd", None, QtGui.QApplication.UnicodeUTF8))
        self.left_label.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "E, MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCategoriesToolBox.setItemText(self.materialCategoriesToolBox.indexOf(self.materialDoseBuildupFactorPage), QtGui.QApplication.translate("RadianceReferenceDialog", "Dose buildup factor", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCategoriesToolBox.setItemText(self.materialCategoriesToolBox.indexOf(self.materialMassAttenuationCoefficientPage), QtGui.QApplication.translate("RadianceReferenceDialog", "Mass attenuation coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.materialsTabWidget), QtGui.QApplication.translate("RadianceReferenceDialog", "Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.editMultiLayeredMaterialButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.addMultiLayeredMaterialButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.nuclideCategoriesToolBox_2.setItemText(self.nuclideCategoriesToolBox_2.indexOf(self.multiLayeredMaterialLayersPage), QtGui.QApplication.translate("RadianceReferenceDialog", "Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("RadianceReferenceDialog", "Multi-layered materials", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("RadianceReferenceDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

import radiance_rc
