# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\gui\radianceaddmaterialdialog.ui'
#
# Created: Fri Jul 15 11:15:47 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RAddMaterialDialog(object):
    def setupUi(self, RAddMaterialDialog):
        RAddMaterialDialog.setObjectName("RAddMaterialDialog")
        RAddMaterialDialog.resize(800, 600)
        RAddMaterialDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(RAddMaterialDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtGui.QLabel(RAddMaterialDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.titleLabel)
        self.materialTitleLineEdit = QtGui.QLineEdit(RAddMaterialDialog)
        self.materialTitleLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.materialTitleLineEdit.setObjectName("materialTitleLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.materialTitleLineEdit)
        self.densityLabel = QtGui.QLabel(RAddMaterialDialog)
        self.densityLabel.setObjectName("densityLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.densityLabel)
        self.materialDensityDoubleSpinBox = QtGui.QDoubleSpinBox(RAddMaterialDialog)
        self.materialDensityDoubleSpinBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.materialDensityDoubleSpinBox.setAccelerated(True)
        self.materialDensityDoubleSpinBox.setMinimum(0.01)
        self.materialDensityDoubleSpinBox.setMaximum(999.99)
        self.materialDensityDoubleSpinBox.setObjectName("materialDensityDoubleSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.materialDensityDoubleSpinBox)
        self.errorLabel = QtGui.QLabel(RAddMaterialDialog)
        self.errorLabel.setEnabled(True)
        self.errorLabel.setStyleSheet("QLabel {\n"
"    background: url(:/Radiance/icons/error.png);\n"
"    background-position: center left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left: 20px;\n"
"}")
        self.errorLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.errorLabel.setObjectName("errorLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.errorLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.materialCategoriesToolBox = QtGui.QToolBox(RAddMaterialDialog)
        self.materialCategoriesToolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.materialCategoriesToolBox.setObjectName("materialCategoriesToolBox")
        self.materialDoseBuildupFactorPage = QtGui.QWidget()
        self.materialDoseBuildupFactorPage.setGeometry(QtCore.QRect(0, 0, 780, 421))
        self.materialDoseBuildupFactorPage.setObjectName("materialDoseBuildupFactorPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.materialDoseBuildupFactorPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.materialDoseBuildupFactorPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.materialMuDTableView = QtGui.QTableView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialMuDTableView.sizePolicy().hasHeightForWidth())
        self.materialMuDTableView.setSizePolicy(sizePolicy)
        self.materialMuDTableView.setMaximumSize(QtCore.QSize(16777215, 30))
        self.materialMuDTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.materialMuDTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.materialMuDTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.materialMuDTableView.setTabKeyNavigation(False)
        self.materialMuDTableView.setAlternatingRowColors(True)
        self.materialMuDTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialMuDTableView.setCornerButtonEnabled(False)
        self.materialMuDTableView.setObjectName("materialMuDTableView")
        self.materialMuDTableView.horizontalHeader().setVisible(False)
        self.materialMuDTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.materialMuDTableView.horizontalHeader().setDefaultSectionSize(85)
        self.materialMuDTableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.materialMuDTableView)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.materialDoseBuildupFactorPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.materialETableView = QtGui.QTableView(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialETableView.sizePolicy().hasHeightForWidth())
        self.materialETableView.setSizePolicy(sizePolicy)
        self.materialETableView.setMinimumSize(QtCore.QSize(0, 0))
        self.materialETableView.setMaximumSize(QtCore.QSize(80, 16777215))
        self.materialETableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.materialETableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.materialETableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.materialETableView.setTabKeyNavigation(False)
        self.materialETableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialETableView.setCornerButtonEnabled(False)
        self.materialETableView.setObjectName("materialETableView")
        self.materialETableView.horizontalHeader().setVisible(False)
        self.materialETableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.materialETableView)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.materialDoseBuildupFactorPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_label = QtGui.QLabel(self.groupBox_3)
        self.top_label.setTextFormat(QtCore.Qt.PlainText)
        self.top_label.setAlignment(QtCore.Qt.AlignCenter)
        self.top_label.setObjectName("top_label")
        self.verticalLayout_4.addWidget(self.top_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_label = QtGui.QLabel(self.groupBox_3)
        self.left_label.setTextFormat(QtCore.Qt.PlainText)
        self.left_label.setObjectName("left_label")
        self.horizontalLayout_2.addWidget(self.left_label)
        self.materialDoseBuildupFactorTableView = QtGui.QTableView(self.groupBox_3)
        self.materialDoseBuildupFactorTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.materialDoseBuildupFactorTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.materialDoseBuildupFactorTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.materialDoseBuildupFactorTableView.setTabKeyNavigation(False)
        self.materialDoseBuildupFactorTableView.setAlternatingRowColors(True)
        self.materialDoseBuildupFactorTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialDoseBuildupFactorTableView.setCornerButtonEnabled(False)
        self.materialDoseBuildupFactorTableView.setObjectName("materialDoseBuildupFactorTableView")
        self.materialDoseBuildupFactorTableView.horizontalHeader().setMinimumSectionSize(60)
        self.horizontalLayout_2.addWidget(self.materialDoseBuildupFactorTableView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.materialCategoriesToolBox.addItem(self.materialDoseBuildupFactorPage, "")
        self.materialMassAttenuationCoefficientPage = QtGui.QWidget()
        self.materialMassAttenuationCoefficientPage.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.materialMassAttenuationCoefficientPage.setObjectName("materialMassAttenuationCoefficientPage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.materialMassAttenuationCoefficientPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.materialMassAttenuationCoefficientTableView = QtGui.QTableView(self.materialMassAttenuationCoefficientPage)
        self.materialMassAttenuationCoefficientTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.materialMassAttenuationCoefficientTableView.setTabKeyNavigation(False)
        self.materialMassAttenuationCoefficientTableView.setAlternatingRowColors(True)
        self.materialMassAttenuationCoefficientTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.materialMassAttenuationCoefficientTableView.setCornerButtonEnabled(False)
        self.materialMassAttenuationCoefficientTableView.setObjectName("materialMassAttenuationCoefficientTableView")
        self.verticalLayout_6.addWidget(self.materialMassAttenuationCoefficientTableView)
        self.materialCategoriesToolBox.addItem(self.materialMassAttenuationCoefficientPage, "")
        self.verticalLayout.addWidget(self.materialCategoriesToolBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.correctnessErrorLabel = QtGui.QLabel(RAddMaterialDialog)
        self.correctnessErrorLabel.setEnabled(True)
        self.correctnessErrorLabel.setStyleSheet("QLabel {\n"
"    background: url(:/Radiance/icons/error.png);\n"
"    background-position: center left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left: 20px;\n"
"}")
        self.correctnessErrorLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.correctnessErrorLabel.setObjectName("correctnessErrorLabel")
        self.horizontalLayout.addWidget(self.correctnessErrorLabel)
        self.addButton = QtGui.QPushButton(RAddMaterialDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Radiance/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setAutoDefault(False)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.cancelButton = QtGui.QPushButton(RAddMaterialDialog)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RAddMaterialDialog)
        self.materialCategoriesToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), RAddMaterialDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RAddMaterialDialog)

    def retranslateUi(self, RAddMaterialDialog):
        RAddMaterialDialog.setWindowTitle(QtGui.QApplication.translate("RAddMaterialDialog", "Add material", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.densityLabel.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Density", None, QtGui.QApplication.UnicodeUTF8))
        self.materialDensityDoubleSpinBox.setSuffix(QtGui.QApplication.translate("RAddMaterialDialog", " g/cm³", None, QtGui.QApplication.UnicodeUTF8))
        self.errorLabel.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Already exists.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("RAddMaterialDialog", "μd", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RAddMaterialDialog", "E, MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RAddMaterialDialog", "Resulting table", None, QtGui.QApplication.UnicodeUTF8))
        self.top_label.setText(QtGui.QApplication.translate("RAddMaterialDialog", "μd", None, QtGui.QApplication.UnicodeUTF8))
        self.left_label.setText(QtGui.QApplication.translate("RAddMaterialDialog", "E, MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCategoriesToolBox.setItemText(self.materialCategoriesToolBox.indexOf(self.materialDoseBuildupFactorPage), QtGui.QApplication.translate("RAddMaterialDialog", "Dose buildup factor", None, QtGui.QApplication.UnicodeUTF8))
        self.materialCategoriesToolBox.setItemText(self.materialCategoriesToolBox.indexOf(self.materialMassAttenuationCoefficientPage), QtGui.QApplication.translate("RAddMaterialDialog", "Mass attenuation coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.correctnessErrorLabel.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Check the correctness of data input.", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("RAddMaterialDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import radiance_rc
